/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 06 12:00:34 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Add_ESTest extends Add_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Add add0 = new Add();
      double double0 = add0.evaluate(0.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Add add0 = new Add();
      double double0 = add0.evaluate(480.547444974893, 0.0);
      assertEquals(480.547444974893, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Add add0 = new Add();
      double double0 = add0.evaluate(0.0, (-1343.686478046854));
      assertEquals((-1343.686478046854), double0, 0.01);
  }
}
