/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 06 12:01:24 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Mul_ESTest extends Mul_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Mul mul0 = new Mul();
      double double0 = mul0.evaluate(1.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Mul mul0 = new Mul();
      double double0 = mul0.evaluate((-1292.53949), 1.0);
      assertEquals((-1292.53949), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Mul mul0 = new Mul();
      double double0 = mul0.evaluate(1368.4, 1.0);
      assertEquals(1368.4, double0, 0.01);
  }
}
