/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 19 13:02:54 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Add_ESTest extends Add_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Add add0 = new Add();
      double double0 = add0.evaluate(0.0, (-493.6296262911884));
      assertEquals((-493.6296262911884), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Add add0 = new Add();
      double double0 = add0.evaluate(1921.9361857421782, 0.0);
      assertEquals(1921.9361857421782, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Add add0 = new Add();
      double double0 = add0.evaluate(0.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }
}
