/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 19 13:02:27 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Constant_ESTest extends Constant_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Constant constant0 = new Constant(0.0);
      double double0 = constant0.evaluate(1642.185984623344);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Constant constant0 = new Constant(2541.6);
      double double0 = constant0.evaluate(2541.6);
      assertEquals(2541.6, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Constant constant0 = new Constant(0.0);
      double double0 = constant0.evaluate();
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Constant constant0 = new Constant(2541.6);
      double double0 = constant0.evaluate();
      assertEquals(2541.6, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Constant constant0 = new Constant((-1005.768612));
      double double0 = constant0.evaluate();
      assertEquals((-1005.768612), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Constant constant0 = new Constant((-1005.768612));
      double double0 = constant0.evaluate((-2522.71815368));
      assertEquals((-1005.768612), double0, 0.01);
  }
}
