/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 19 13:06:20 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Factory_ESTest extends Factory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Factory factory0 = new Factory();
      Operation operation0 = factory0.o('6');
      assertNull(operation0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Factory factory0 = new Factory();
      Operation operation0 = factory0.o('/');
      assertNotNull(operation0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Factory factory0 = new Factory();
      Operation operation0 = factory0.o('-');
      assertNotNull(operation0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Factory factory0 = new Factory();
      Operation operation0 = factory0.o('+');
      assertNotNull(operation0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Factory factory0 = new Factory();
      Operation operation0 = factory0.o('*');
      assertNotNull(operation0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Factory factory0 = new Factory();
      Expresion expresion0 = factory0.x();
      assertNotNull(expresion0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Factory factory0 = new Factory();
      Constant constant0 = (Constant)factory0.c('+');
      Exp exp0 = (Exp)factory0.o('^');
      assertNotNull(exp0);
      
      factory0.f(exp0, constant0, constant0);
      assertEquals(43.0, constant0.evaluate(), 0.01);
  }
}
