/*
 * This file was automatically generated by EvoSuite
 * Thu Mar 19 13:03:35 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Integral_ESTest extends Integral_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integral integral0 = new Integral((-844.85), 212.689386, 212.689386);
      Constant constant0 = new Constant(212.689386);
      double double0 = integral0.integrate(constant0);
      assertEquals(226183.87458528503, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integral integral0 = new Integral((-844.85), 212.689386, 212.689386);
      Variable variable0 = new Variable();
      double double0 = integral0.integrate(variable0);
      assertEquals((-446085.3896399301), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integral integral0 = new Integral(722.7728, 1033.751577002321, (-893.4020258141064));
      Sub sub0 = new Sub();
      Variable variable0 = new Variable();
      Function function0 = new Function(sub0, variable0, variable0);
      // Undeclared exception!
      integral0.integrate(function0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Integral integral0 = new Integral((-1.0), 1316.613, (-1.0));
      // Undeclared exception!
      try { 
        integral0.integrate((Expresion) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("Integral", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Integral integral0 = new Integral((-844.85), 212.689386, 212.689386);
      Sub sub0 = new Sub();
      Variable variable0 = new Variable();
      Function function0 = new Function(sub0, variable0, variable0);
      double double0 = integral0.integrate(function0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Integral integral0 = new Integral((-1.0), (-1.0), 0.0);
      Variable variable0 = new Variable();
      double double0 = integral0.integrate(variable0);
      assertEquals(0.0, double0, 0.01);
  }
}
