/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 06 12:02:44 GMT 2020
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Variable_ESTest extends Variable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Variable variable0 = new Variable();
      double double0 = variable0.evaluate(0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Variable variable0 = new Variable();
      double double0 = variable0.evaluate((-4927.8413963355));
      assertEquals((-4927.8413963355), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Variable variable0 = new Variable();
      double double0 = variable0.evaluate(1.0);
      assertEquals(1.0, double0, 0.01);
  }
}
